springdoc:
  api-docs:
    enabled: true
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger.html

security:
  jwt:
    public-key: classpath:app.pub
    private-key: classpath:app.ket

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope: read:user
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: "10s"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo
  jpa:
    open-in-view: false
  datasource:
    hikari:
      maxLifetime: '2000000'
      poolName: SpringBootHikariCP
      connectionTimeout: '30000'
      idleTimeout: '30000'
      minimumIdle: '5'
      maximumPoolSize: '20'
      schema: public
    url: ${DATASOURCE_URL}
    type: com.zaxxer.hikari.HikariDataSource
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  port: 8091
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
application:
  frontend:
    url: http://localhost:3000
  formatted-version: v1.0.0
  title: TicketsIFSP-API
